### ISSUE TITLE
FCMS 0.10 via EDMarketConnector 5.1.0 does not update market

### ISSUE THREAD

**Issue by pan-mroku** [anthonylangsworth/FCMS#3]
In Inara and on fleetcarrier.space the only market info that is shown is from black market. The position, docking permissions, even cargo contents are updated correctly. The info from "normal" market is not visible in any of the two sites.

CMDR name, email, fleetcarrier api matches.

It's been like that for some time now so I don't think it's a regression.

**Comment by anthonylangsworth** [comment]
Hi @pan-mroku . I am sorry you are having these issues but the FCMS plug-in cannot help you. The FCMS plug-in does not upload market data from your carrier to Inara or other sites. The plug-in only uploads jump details. Inara and https://fleetcarrier.space pull market data from Frontier via the companion API and/or your journal file entries.

You mention this problem occurs on both Inara and https://fleetcarrier.space. Therefore, I suspect this is a problem with the game. Perhaps raise this to Inara or https://fleetcarrier.space and see whether others are having the same problem.

Good luck!
