### ISSUE TITLE
Elite Dangerous Discovery plugin

### ISSUE THREAD

**Issue by robbyxp1** [anthonylangsworth/FCMS#4]
Hi,

No idea if you'd be interested, but we recently did a EDD plug in (in c#) for canonn to report codex/scan organic entries..

https://github.com/canonn-science/EDDCanonn

A mild variation of that code would all that would be required to report carrier jumps to you via an EDD plugin.

Cheers

Robby (EDDiscovery author).

**Comment by anthonylangsworth** [comment]
Hi Robby,

Thanks for reaching out. However, this repository is a fork of the FCMS plug-in that declutters the UI and automates the plug-in's installation and upgrade. Chat to Absolver on the EDCD Discord (link: https://discord.gg/47QYvP9A) about FCMS and its plug-in.

Also, thanks for working on a great plug-in. I use it when I go through an exploration phase, such as my trip out to Colonia and Sag A* earlier this year.

Regards,
Anthony (a.k.a. CMDR Akton)
